#!/usr/bin/env ansible-playbook
---
- hosts: all

  pre_tasks:
    - name: Check Ansible version
      ansible.builtin.assert:
        that: ansible_version.full is version_compare('2.9', '>=')
        msg: The Ansible version is too old for this playbook

  tasks:
    - name: Execute apt update if the last one is more than 1 hour ago
      become: yes
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_pkg_mgr == "apt"

    - name: Install pip and Ansible
      ansible.builtin.include_role: { name: geerlingguy.pip }
      vars:
        ansible_become: yes
        pip_install_packages: [ansible]
