#!/usr/bin/env ansible-playbook
---
- name: Main play
  hosts: all

  pre_tasks:
    - name: Check Ansible version
      ansible.builtin.assert:
        that: ansible_version.full is version_compare('2.9', '>=')
        msg: The Ansible version is too old for this playbook

  tasks:
    - name: Execute apt update if the last one is more than 1 hour ago
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_pkg_mgr == "apt"

    - name: Ensure some packages are installed
      become: true
      ansible.builtin.package:
        name:
          - git # needed by Ansible Lint
          - sshpass # Needed by Ansible for password-based SSH login
          - python3-pip # Needed by the "ansible.builtin.pip" Ansible module

    - name: Install Ansible and Ansible Lint with pip as unprivileged user
      ansible.builtin.pip:
        extra_args: --user
        name: [ansible, ansible-lint]
